### ISSUE TITLE
Webpack Config

### ISSUE THREAD

**Issue by DZuz14** [T-Streets/cosmicFox#3]
Not answering this unless you conquer the navbar scrolling feature.

**Comment by spaceSamura1** [comment]
💪🏼

**Comment by spaceSamura1** [comment]
One thing i wanted to specifically ask you about the webpack config is that im not getting hot reloading with my styling. Does that have to do with the change you recommended earlier?

**Comment by DZuz14** [comment]
I cant see what you changed. Did you make any changes to the webpack config? Commit history says you haven't made changed to it atleast 7 days ago. Can you make a branch and change the webpack config to what you are saying you did?

I will checkout the branch on my local machine and see what you have.

**Comment by spaceSamura1** [comment]
Nothing has changed, its something I have yet to figure out and was meaning to ask you.

**Comment by DZuz14** [comment]
Can check it in the am. Where are you located by the way? I live in Boston.

**Comment by spaceSamura1** [comment]
Yeah no worries! I’m in LA

**Comment by DZuz14** [comment]
So you'll get better at this, but make sure to pay close attention to errors and output in your console. I ran the `npm run start:dev` command and in the console, and extract text plugin gave some output about an 'entry point being undefined'. 

With a quick search for **"extract text plugin entry point undefined"** in google, I was able to find a Github Issue thread where people were suggesting to upgrade to [https://github.com/webpack-contrib/mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)

It looks like you are using Webpack 4, which people on the thread were complaining that it did not work well with extract text plugin.

**Comment by DZuz14** [comment]
Any other stuff you need help with? Feel free to open up issues on the board. This is good practice.

**Comment by spaceSamura1** [comment]
Ok cool ill check into that link. 

Thats all for now, I really appreciate all of your help! I have already learned a ton from you and I cant thank you enough for the nudges in the right direction

**Comment by DZuz14** [comment]
No prob. Most of the times that's all people need. Cheers!

**Comment by spaceSamura1** [comment]
Hey Dan is it possible you could help me with an issue im having? Here is
the repo: https://github.com/T-Streets/feather_and_ash

the issue is im trying to grab data from the form component using axios. Im
sending the post request to a route specified in my index.js in the root
directory. Index.js is listening on port 3000 the react app is being run
concurrently on 8080. In my console i can see that im getting a 404 error
because the react app is looking for the route on 8080 which makes sense as
to why this isnt working. I although am not sure how to solve this because
i believe to have the proxy set up correctly in my package.json of the
client directory. Through some research im getting the idea that this is
actually a webpack issue but not 100% sure. If you could shed some light on
this would be epic! thanks again for all your help.
